# Generated by Django 4.2.3 on 2023-07-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='kpi',
            old_name='name',
            new_name='employee_kpi_name',
        ),
    ]
